// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const missingConfigError = {
  message: "Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.",
  details: null,
  hint: null,
  code: "SUPABASE_NOT_CONFIGURED",
};

const createNoopResult = (data: unknown) => ({
  data,
  error: missingConfigError,
  count: null,
  status: 400,
  statusText: "Supabase not configured",
});

const createNoopQueryBuilder = () => {
  const builder: any = {};
  const chain = () => builder;

  [
    "select",
    "insert",
    "update",
    "upsert",
    "delete",
    "eq",
    "neq",
    "in",
    "not",
    "is",
    "lt",
    "lte",
    "gt",
    "gte",
    "ilike",
    "like",
    "contains",
    "containedBy",
    "or",
    "order",
    "limit",
    "range",
  ].forEach((method) => {
    builder[method] = chain;
  });

  builder.single = async () => createNoopResult(null);
  builder.maybeSingle = async () => createNoopResult(null);

  builder.then = (onFulfilled: any, onRejected: any) => Promise.resolve(createNoopResult([])).then(onFulfilled, onRejected);
  builder.catch = (onRejected: any) => Promise.resolve(createNoopResult([])).catch(onRejected);
  builder.finally = (onFinally: any) => Promise.resolve(createNoopResult([])).finally(onFinally);

  return builder;
};

const createNoopSupabaseClient = () => {
  const noopAuth = {
    getSession: async () => ({ data: { session: null }, error: missingConfigError }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => undefined } } }),
    signUp: async () => ({ data: { user: null, session: null }, error: missingConfigError }),
    signInWithPassword: async () => ({ data: { user: null, session: null }, error: missingConfigError }),
    signOut: async () => ({ error: null }),
  };

  const noopChannel = {
    on: () => noopChannel,
    subscribe: () => noopChannel,
    unsubscribe: () => undefined,
  };

  return {
    auth: noopAuth,
    from: () => createNoopQueryBuilder(),
    rpc: async () => ({ data: null, error: missingConfigError }),
    channel: () => noopChannel,
    removeChannel: () => Promise.resolve("ok" as const),
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : (createNoopSupabaseClient() as unknown as SupabaseClient<Database>);

if (!isSupabaseConfigured) {
  console.warn(missingConfigError.message);
}
